import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

import 'lyricClass.dart';

class Body extends StatefulWidget {
  const Body({Key? key}) : super(key: key);

  @override
  State<Body> createState() => _BodyState();
}

class _BodyState extends State<Body> {
  String lyricData = '';

  Future getLyrics() async {
    //print('test');

    http.Response response;

    response = await http.get(
      Uri.parse('https://api.lyrics.ovh/v1/iron maiden/the trooper'),
    );

    //print(response.body);

    if (response.statusCode == 200) {
      //print('test1');

      Autogenerated autogenerated =
          Autogenerated.fromJson(jsonDecode(response.body));

      setState(() {
        lyricData = autogenerated.lyrics!;
      });
    } else {
      setState(() {
        lyricData = 'not found';
      });
    }
  }

  @override
  void initState() {
    getLyrics();
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(child: Text(lyricData)),
    );
  }
}
