import 'dart:convert';

import 'package:http/http.dart' as http;

import 'lyricClass.dart';

class Networking {
  dynamic lyricData;
  String songNameNetwork;
  String artistNameNetwork;

  Networking({required this.artistNameNetwork, required this.songNameNetwork});
  Future getLyrics() async {
    //print('test');

    http.Response response;
    //print(songNameNetwork);

    response = await http.get(
      Uri.parse(
          'https://api.lyrics.ovh/v1/$artistNameNetwork/$songNameNetwork'),
    );

    //print(response.body);

    if (response.statusCode == 200) {
      //print('test1');

      Autogenerated autogenerated =
          Autogenerated.fromJson(jsonDecode(response.body));

      //print(autogenerated.lyrics);

      //print(autogenerated.toJson().runtimeType);

      //print(autogenerated.toJson());

      lyricData = autogenerated.toJson();

      //return  autogenerated.lyrics;
    } else {
      lyricData = 'none';
    }
  }

  dynamic hello() {
    //print(lyricData);
    //print(songNameNetwork);
    return lyricData;
  }
}
