import 'dart:convert';

import 'package:http/http.dart' as http;

import 'lyricClass.dart';

class Networking {
  String lyricData = '';

  Future getLyrics() async {
    //print('test');

    http.Response response;

    response = await http.get(
      Uri.parse('https://api.lyrics.ovh/v1/iron maiden/the trooper'),
    );

    //print(response.body);

    if (response.statusCode == 200) {
      //print('test1');

      Autogenerated autogenerated =
          Autogenerated.fromJson(jsonDecode(response.body));
    }
  }
}
